language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  # - yarn test
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: http://hadabo.github.io/oreo-clicker
  project: ./build/
on:
  branch: master
